export type FieldType = 'text' | 'number' | 'textarea' | 'date' | 'select' | 'multiselect' | 'password' | 'file'

export type ResourceField = {
  key: string
  label: string
  type: FieldType
  required?: boolean
  options?: { label: string; value: string | number }[]
  optionsKey?: string
  readKey?: string
}

export type ResourceConfig = {
  key: string
  title: string
  endpoint: string
  columns: { key: string; label: string; tooltip?: string }[]
  fields: ResourceField[]
  multipart?: boolean
  readonly?: boolean
  actionHeader?: string
}

export const resources: ResourceConfig[] = [
  {
    key: 'items',
    title: '硬件',
    endpoint: '/items',
    columns: [
      { key: 'id', label: '编号' },
      { key: 'label', label: '标签' },
      { key: 'itemType', label: '硬件类型' },
      { key: 'manufacturer', label: '厂商' },
      { key: 'model', label: '型号' },
      { key: 'sn', label: '设备序列号' },
      { key: 'purchasedate', label: '采购日期' },
      { key: 'warrantyRemain', label: '维保剩余天数' },
      { key: 'ipv4', label: 'IPv4' },
      { key: 'dpt', label: '所属部门' },
      { key: 'principal', label: '负责人' },
      { key: 'status', label: '状态' },
      { key: 'location', label: '地点' },
      { key: 'rack', label: '机架' },
      { key: 'function', label: '用途' },
      { key: 'software', label: '软件' },
      { key: 'remadmip', label: '远程管理IP' },
      { key: 'tags', label: '标记' },
    ],
    fields: [
      { key: 'label', label: '标签', type: 'text' },
      { key: 'itemTypeId', readKey: 'itemtypeid', label: '硬件类型', type: 'select', required: true, optionsKey: 'itemtypes' },
      { key: 'isPart', readKey: 'ispart', label: '从属部件', type: 'number', required: true },
      { key: 'rackMountable', readKey: 'rackmountable', label: '机架式', type: 'number', required: true },
      { key: 'manufacturerId', readKey: 'manufacturerid', label: '厂商', type: 'select', required: true, optionsKey: 'agents' },
      { key: 'model', label: '型号', type: 'text', required: true },
      { key: 'uSize', readKey: 'usize', label: '大小(U)', type: 'number' },
      { key: 'sn', label: '设备序列号', type: 'text' },
      { key: 'sn2', label: '序列号2', type: 'text' },
      { key: 'sn3', label: 'Service Tag', type: 'text' },
      { key: 'comments', label: '注释', type: 'textarea' },
      { key: 'principal', label: '负责人', type: 'text', required: true },
      { key: 'status', readKey: 'status', label: '状态', type: 'select', required: true, optionsKey: 'statustypes' },
      { key: 'dptId', readKey: 'dptid', label: '所属部门', type: 'select', optionsKey: 'dpttypes' },
      { key: 'locationId', readKey: 'locationid', label: '地点', type: 'select', optionsKey: 'locations' },
      { key: 'locAreaId', readKey: 'locareaid', label: '区域/房间', type: 'select', optionsKey: 'locareas' },
      { key: 'rackId', readKey: 'rackid', label: '机架', type: 'select', optionsKey: 'racks' },
      { key: 'rackPosition', readKey: 'rackposition', label: '机架位置', type: 'number' },
      { key: 'rackPosDepth', readKey: 'rackposdepth', label: '机架深度位', type: 'number' },
      { key: 'function', label: '用途', type: 'text' },
      { key: 'userId', readKey: 'userid', label: '使用人', type: 'select', optionsKey: 'users' },
      { key: 'purchaseDate', readKey: 'purchasedate', label: '采购日期', type: 'date' },
      { key: 'warrantyMonths', readKey: 'warrantymonths', label: '维保月数', type: 'number' },
      { key: 'warrInfo', readKey: 'warrinfo', label: '维保信息', type: 'textarea' },
      { key: 'maintenanceInfo', readKey: 'maintenanceinfo', label: '维护记录', type: 'textarea' },
      { key: 'hd', label: '硬盘', type: 'text' },
      { key: 'ram', label: '内存', type: 'text' },
      { key: 'cpu', label: 'CPU型号', type: 'text' },
      { key: 'cpuNo', readKey: 'cpuno', label: 'CPU数量', type: 'text' },
      { key: 'coresPerCpu', readKey: 'corespercpu', label: '每CPU核心数', type: 'text' },
      { key: 'raid', label: 'Raid卡型号', type: 'text' },
      { key: 'raidConfig', readKey: 'raidconfig', label: 'Raid配置', type: 'textarea' },
      { key: 'macs', label: 'MACs', type: 'text' },
      { key: 'ipv4', label: 'IPv4', type: 'text' },
      { key: 'ipv6', label: 'IPv6', type: 'text' },
      { key: 'remAdmIp', readKey: 'remadmip', label: '远程管理IP', type: 'text' },
      { key: 'dnsName', readKey: 'dnsname', label: '管理跳线', type: 'text' },
      { key: 'panelPort', readKey: 'panelport', label: 'Bond名称', type: 'text' },
      { key: 'switchId', readKey: 'switchid', label: '交换机', type: 'select', optionsKey: 'items_ref' },
      { key: 'switchPort', readKey: 'switchport', label: '业务跳线', type: 'text' },
      { key: 'ports', label: '网络端口', type: 'text' },
      { key: 'purchPrice', readKey: 'purchprice', label: '采购价格(￥)', type: 'text' },
      { key: 'origin', label: '供应商', type: 'text' },
      { key: 'itemLinks', label: '内部硬件关联', type: 'multiselect', optionsKey: 'items_ref' },
      { key: 'invoiceLinks', label: '关联单据', type: 'multiselect', optionsKey: 'invoices_ref' },
      { key: 'softwareLinks', label: '关联软件', type: 'multiselect', optionsKey: 'software_ref' },
      { key: 'contractLinks', label: '关联合同', type: 'multiselect', optionsKey: 'contracts_ref' },
      { key: 'fileLinks', label: '关联文件', type: 'multiselect', optionsKey: 'files_ref' },
    ],
  },
  {
    key: 'software',
    title: '软件',
    endpoint: '/software',
    columns: [
      { key: 'id', label: '编号' },
      { key: 'manufacturer', label: '厂商' },
      { key: 'title', label: '标题' },
      { key: 'version', label: '版本' },
      { key: 'purchdate', label: '采购日期' },
      { key: 'maintend', label: '维护结束', tooltip: '维护截止日期' },
      { key: 'slicenseinfo', label: '许可信息' },
      { key: 'sinfo', label: '其它信息' },
      { key: 'tags', label: '标记' },
      { key: 'qty', label: '数量' },
      { key: 'vendor', label: '供应商', tooltip: '从相关单据获取' },
      { key: 'invoice', label: '单据' },
      { key: 'installedon', label: '安装于' },
    ],
    fields: [
      { key: 'title', readKey: 'stitle', label: '标题', type: 'text', required: true },
      { key: 'version', readKey: 'sversion', label: '版本', type: 'text', required: true },
      { key: 'manufacturerId', readKey: 'manufacturerid', label: '厂商', type: 'select', required: true, optionsKey: 'agents' },
      { key: 'purchaseDate', readKey: 'purchdate', label: '采购日期', type: 'date' },
      { key: 'licenseQty', readKey: 'licqty', label: '授权数量', type: 'number' },
      {
        key: 'licenseType',
        readKey: 'lictype',
        label: '授权类型',
        type: 'select',
        options: [
          { label: '按设备', value: 0 },
          { label: '按CPU', value: 1 },
          { label: '按核心', value: 2 },
        ],
      },
      { key: 'slicenseInfo', readKey: 'slicenseinfo', label: '许可信息', type: 'textarea' },
      { key: 'info', readKey: 'sinfo', label: '其它信息', type: 'textarea' },
      { key: 'itemLinks', label: '关联硬件', type: 'multiselect', optionsKey: 'items_ref' },
      { key: 'invoiceLinks', label: '关联单据', type: 'multiselect', optionsKey: 'invoices_ref' },
      { key: 'contractLinks', label: '关联合同', type: 'multiselect', optionsKey: 'contracts_ref' },
      { key: 'fileLinks', label: '关联文件', type: 'multiselect', optionsKey: 'files_ref' },
    ],
  },
  {
    key: 'invoices',
    title: '单据',
    endpoint: '/invoices',
    actionHeader: '操作',
    columns: [
      { key: 'id', label: '编号' },
      { key: 'vendor', label: '供应商' },
      { key: 'buyer', label: '采购方' },
      { key: 'date', label: '日期' },
      { key: 'number', label: '订单编号' },
      { key: 'description', label: '描述' },
      { key: 'files', label: '关联文件' },
    ],
    fields: [
      { key: 'number', label: '订单编号', type: 'text', required: true },
      { key: 'vendorId', readKey: 'vendorid', label: '供应商', type: 'select', required: true, optionsKey: 'agents' },
      { key: 'buyerId', readKey: 'buyerid', label: '采购方', type: 'select', required: true, optionsKey: 'agents' },
      { key: 'date', readKey: 'date', label: '日期', type: 'date', required: true },
      { key: 'description', label: '描述', type: 'textarea' },
      { key: 'itemLinks', label: '关联硬件', type: 'multiselect', optionsKey: 'items_ref' },
      { key: 'softwareLinks', label: '关联软件', type: 'multiselect', optionsKey: 'software_ref' },
      { key: 'contractLinks', label: '关联合同', type: 'multiselect', optionsKey: 'contracts_ref' },
      { key: 'fileLinks', label: '关联文件', type: 'multiselect', optionsKey: 'files_ref' },
    ],
  },
  {
    key: 'agents',
    title: '代理',
    endpoint: '/agents',
    columns: [
      { key: 'id', label: '编号' },
      { key: 'type', label: '类型' },
      { key: 'title', label: '名称' },
      { key: 'contactinfo', label: '合同信息' },
      { key: 'contacts', label: '合同' },
    ],
    fields: [
      { key: 'title', label: '名称', type: 'text', required: true },
      {
        key: 'types',
        readKey: 'type',
        label: '类型',
        type: 'multiselect',
        options: [
          { label: '供应商', value: 4 },
          { label: '软件厂商', value: 2 },
          { label: '硬件厂商', value: 8 },
          { label: '采购方', value: 1 },
          { label: '承包方', value: 16 },
        ],
      },
      { key: 'contactInfo', readKey: 'contactinfo', label: '联系方式', type: 'textarea' },
    ],
  },
  {
    key: 'files',
    title: '文件',
    endpoint: '/files',
    multipart: true,
    actionHeader: '操作',
    columns: [
      { key: 'id', label: '编号' },
      { key: 'typedesc', label: '类型' },
      { key: 'title', label: '标题' },
      { key: 'fname', label: '文件' },
      { key: 'links', label: '关联' },
    ],
    fields: [
      { key: 'title', label: '标题', type: 'text', required: true },
      { key: 'typeId', readKey: 'type', label: '类型', type: 'select', required: true, optionsKey: 'filetypes' },
      { key: 'date', readKey: 'date', label: '签署日期', type: 'date', required: true },
      { key: 'file', label: '上传文件', type: 'file' },
      { key: 'itemLinks', label: '关联硬件', type: 'multiselect', optionsKey: 'items_ref' },
      { key: 'softwareLinks', label: '关联软件', type: 'multiselect', optionsKey: 'software_ref' },
      { key: 'invoiceLinks', label: '关联单据', type: 'multiselect', optionsKey: 'invoices_ref' },
      { key: 'fileLinks', label: '关联文件', type: 'multiselect', optionsKey: 'files_ref' },
      { key: 'contractLinks', label: '关联合同', type: 'multiselect', optionsKey: 'contracts_ref' },
    ],
  },
  {
    key: 'contracts',
    title: '合同',
    endpoint: '/contracts',
    columns: [
      { key: 'id', label: '编号' },
      { key: 'parentid', label: '上级编号' },
      { key: 'type', label: '类型' },
      { key: 'number', label: '数量' },
      { key: 'title', label: '标题' },
      { key: 'startdate', label: '开始日期' },
      { key: 'currentenddate', label: '结束日期' },
    ],
    fields: [
      { key: 'title', label: '标题', type: 'text', required: true },
      { key: 'number', label: '数量', type: 'text', required: true },
      { key: 'typeId', readKey: 'type', label: '合同类型', type: 'select', required: true, optionsKey: 'contracttypes' },
      { key: 'subTypeId', readKey: 'subtype', label: '合同子类型', type: 'select', optionsKey: 'contractsubtypes' },
      { key: 'parentId', readKey: 'parentid', label: '上级合同', type: 'select', optionsKey: 'contracts_ref' },
      { key: 'contractorId', readKey: 'contractorid', label: '承包方', type: 'select', required: true, optionsKey: 'agents' },
      { key: 'startDate', readKey: 'startdate', label: '开始日期', type: 'date', required: true },
      { key: 'currentEndDate', readKey: 'currentenddate', label: '结束日期', type: 'date', required: true },
      { key: 'renewals', label: '续签信息', type: 'text' },
      { key: 'totalCost', readKey: 'totalcost', label: '总成本', type: 'text' },
      { key: 'description', label: '合同描述', type: 'textarea' },
      { key: 'comments', label: '注释', type: 'textarea' },
      { key: 'itemLinks', label: '关联硬件', type: 'multiselect', optionsKey: 'items_ref' },
      { key: 'softwareLinks', label: '关联软件', type: 'multiselect', optionsKey: 'software_ref' },
      { key: 'invoiceLinks', label: '关联单据', type: 'multiselect', optionsKey: 'invoices_ref' },
      { key: 'fileLinks', label: '关联文件', type: 'multiselect', optionsKey: 'files_ref' },
    ],
  },
  {
    key: 'locations',
    title: '地点',
    endpoint: '/locations',
    multipart: true,
    columns: [
      { key: 'id', label: '编号' },
      { key: 'name', label: '地点名称/建筑名称' },
      { key: 'floor', label: '楼层' },
      { key: 'areaname', label: '区域/办公室' },
      { key: 'floorplanfn', label: '建筑平面图' },
    ],
    fields: [
      { key: 'name', label: '地点名称', type: 'text', required: true },
      { key: 'floor', label: '楼层', type: 'text', required: true },
      { key: 'file', label: '建筑平面图', type: 'file' },
    ],
  },
  {
    key: 'users',
    title: '用户',
    endpoint: '/users',
    columns: [
      { key: 'id', label: '编号' },
      { key: 'username', label: '用户名' },
      { key: 'userdesc', label: '用户描述' },
      { key: 'usertype', label: '类型' },
      { key: 'itemCount', label: '硬件' },
    ],
    fields: [
      { key: 'username', label: '用户名', type: 'text', required: true },
      { key: 'password', readKey: 'pass', label: '密码', type: 'password' },
      { key: 'userDesc', readKey: 'userdesc', label: '用户描述', type: 'text' },
      {
        key: 'userType',
        readKey: 'usertype',
        label: '类型',
        type: 'select',
        options: [
          { label: '完全访问', value: 0 },
          { label: '只读', value: 1 },
        ],
      },
    ],
  },
  {
    key: 'racks',
    title: '机架',
    endpoint: '/racks',
    columns: [
      { key: 'id', label: '编号' },
      { key: 'occupation', label: '在用' },
      { key: 'population', label: '硬件', tooltip: '多少硬件被分配到这个机架' },
      { key: 'usize', label: '高度(U)*' },
      { key: 'depth', label: '深度' },
      { key: 'location', label: '地点' },
      { key: 'area', label: '区域/房间' },
      { key: 'label', label: '标签' },
    ],
    fields: [
      { key: 'label', label: '标签', type: 'text', required: true },
      { key: 'locationId', readKey: 'locationid', label: '地点', type: 'select', required: true, optionsKey: 'locations' },
      { key: 'locAreaId', readKey: 'locareaid', label: '区域', type: 'select', optionsKey: 'locareas' },
      { key: 'uSize', readKey: 'usize', label: '高度(U)*', type: 'number', required: true },
      { key: 'depth', label: '深度(mm)', type: 'number', required: true },
      { key: 'model', label: '型号', type: 'text' },
      {
        key: 'revNums',
        readKey: 'revnums',
        label: '编号方向',
        type: 'select',
        options: [
          { value: 0, label: '1=Bottom' },
          { value: 1, label: '1=Top' },
        ],
      },
      { key: 'comments', label: '注释', type: 'textarea' },
    ],
  },
]

export const resourceMap = Object.fromEntries(resources.map((r) => [r.key, r])) as Record<string, ResourceConfig>
